name: 🚫 Add app rejection fixes report
description: Suggest an addition to this list.
title: '🚫 Add <rejection fixes report>'
labels: ['addition']
body:
  - type: textarea
    attributes:
      label: 🚫 Rejection Message
      description: |
        The rejection message you received from Apple. For Example:

        ```markdown
        ## 🚫 Guideline 2.3 - Performance - Accurate Metadata

        We noticed that your app’s metadata includes the following information, which is not relevant to ....

        What’ new text showed iOS reference.

        **Q: Next Steps**

        To resolve this issue, please revise or remove this content from your app’s metadata. ....
        ```
      placeholder: Please provide the rejection message you received from Apple.

    validations:
      required: true
  - type: textarea
    attributes:
      label: 💯 Rejection Fixes
      description: |
        The steps you took to fix the rejection. For Example:

        ```markdown
        > [!TIP]  
        > **A: 💯 Rejection Fixes**
        > 
        > While mentioning macOS in the release notes for an iOS app is not problematic, ....
        ```
      placeholder: Please provide the steps you took to fix the rejection.

    validations:
      required: true