name: CI/CD
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Create idoc config.
        run: |
          cat > idoc.yml << EOF
          site: "App Rejection Fixes"
          description: This repository documents the various reasons why apps were rejected during the App Store review process and provides solutions to resolve these issues.
          keywords: App Rejection, App Store Review, Rejection Reasons, App Submission, Developer Resources, Review Process, App Approval, Common Issues, Solutions, Review Issues
          favicon: logo.svg
          logo: ./logo.svg
          openSource: https://github.com/jaywcjlove/app-rejection-fixes
          homepage: https://wangchujiang.com/app-rejection-fixes/
          meta:
            - <meta name="author" content="Kenny Wong">
            - <meta property="og:site_name" content="<%= site %>">
            - <meta property="og:url" content="<%=homepage%><%=RESOLVE_PATH%>">
            - <meta property="og:image" content="<%=homepage%>logo.svg">
            - <meta property="og:type" content="application">
            - <meta property="og:title" content="<%= site %>">
            - <meta property="og:description" content="<%= description%>">
            - <meta property="twitter:site" content="@jaywcjlove">
            - <meta property="twitter:creator" content="jaywcjlove">
            - <meta property="twitter:card" content="summary_large_image">
            - <meta property="twitter:title" content="<%= site %> - <%= description%>">
            - <meta property="twitter:description" content="<%= description%>">
          menus:
            Home: index.html
            Apps: 
              url: https://wangchujiang.com/#/app
              target: __blank
            About: 
              url: https://wangchujiang.com/#/about
              target: __blank
          footer: |
            <a href="https://wangchujiang.com/#/projects" target="_blank">Projects</a> • 
            <a href="https://wangchujiang.com/#/sponsor" target="_blank">Sponsor</a> • 
            <a href="https://wangchujiang.com/#/app" target="_blank">More Apps</a><br /><br />
            Generated by <a href="https://github.com/jaywcjlove/idoc" target="_blank">idoc</a> v{{idocVersion}}      
          EOF

      - run: npm install idoc@1 -g
      - run: idoc

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          commit_message: ${{ github.event.head_commit.message }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist